apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: adminserver
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      name: adminserver-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: jobservice
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      name: jobservice-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mysql
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mysql-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: nginx
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      name: nginx-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: registry
  spec:
    ports:
    - name: repo
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: debug
      port: 5001
      protocol: TCP
      targetPort: 5001
    selector:
      name: registry-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ui
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      name: ui-apps
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
